services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "8080:8000"
    volumes:
      - $PWD/backend:/dev_backend
      - database_data:/vector_index
    environment:
      - EMBEDDING_MODEL_NAME=nomic-embed-text
      - EMBEDDING_MODEL_OUTPUT_SIZE=768
      - CHAT_MODEL_NAME=llama3.2:1b
      - INSTRUCT_MODEL_NAME=llama3.2:1b-instruct-q4_0
    stdin_open: true
    tty: true
    command: 
      - /bin/bash

  webui:
    build: 
      context: webui
      dockerfile: Dockerfile_webui
    container_name: webui
    volumes:
      - $PWD/webui:/dev_webui
    ports:
      - "80:8501"
    stdin_open: true
    tty: true
    command: 
      - /bin/bash

volumes:
  database_data:
  ollama_data:

