services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    # ports:
    #   - "11434:11434"
    # if gpu uncomment the following
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  webui:
    build:
      context: webui
      dockerfile: Dockerfile_webui
    container_name: webui
    ports:
      - "80:80"
  
  # database:
  #   image: todo

volumes:
  database_data:

