services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    # ports:
    #   - "11434:11434"
    # if gpu uncomment the following
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  webui:
    build:
      context: webui
      dockerfile: Dockerfile_webui
    container_name: webui
    ports:
      - "80:80"
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "8080:8000"
    environment:
      - EMBEDDING_MODEL_NAME=nomic-embed-text
      - EMBEDDING_VECTOR_SIZE=768
      # - INSTRUCT_MODEL_NAME=llama3.2:1b-instruct

volumes:
  database_data:

