services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  webui:
    build:
      context: webui
      dockerfile: Dockerfile_webui
    container_name: webui
    ports:
      - "80:8501"
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile_backend
    container_name: backend
    volumes:
      - database_data:/vector_index
    environment:
      - EMBEDDING_MODEL_NAME=nomic-embed-text
      - EMBEDDING_MODEL_OUTPUT_SIZE=768
      - CHAT_MODEL_NAME=llama3.2:1b
      - INSTRUCT_MODEL_NAME=llama3.2:1b-instruct-q4_0

volumes:
  database_data:
  ollama_data: