services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  datastore:
    build:
      context: datastore
      dockerfile: Dockerfile_datastore
    container_name: datastore
    volumes:
      - database_data:/vector_index
      - uploaded_files_data:/uploaded_files
    restart: unless-stopped
    depends_on:
      - backend

  document_converter:
    build:
      context: document_converter
      dockerfile: Dockerfile_documentconverter
    container_name: document_converter
    volumes:
      - document_converter_data:/converter_cache
      - uploaded_files_data:/uploaded_files
    restart: unless-stopped
    depends_on:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile_backend
    container_name: backend
    volumes:
      - database_data:/vector_index
      - uploaded_files_data:/uploaded_files
    environment:
      - EMBEDDING_MODEL_NAME=nomic-embed-text
      - EMBEDDING_MODEL_OUTPUT_SIZE=768
      - CHAT_MODEL_NAME=llama3.2:1b
      - INSTRUCT_MODEL_NAME=llama3.2:1b-instruct-q4_0
    restart: unless-stopped
    depends_on:
      - ollama

  webui:
    build: 
      context: webui
      dockerfile: Dockerfile_webui
    container_name: webui
    ports:
      - "80:8501"
    restart: unless-stopped
    depends_on:
      - backend


volumes:
  database_data:
  ollama_data:
  document_converter_data:
  uploaded_files_data:

