FROM python:3.12.7

WORKDIR /webui

COPY requirements.txt .

RUN pip install --no-cache -r requirements.txt

COPY . .

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

CMD ["streamlit", "run", "src/main.py", "--server.headless", "true"]